name: Build Android APK

on:
  push:
    branches: [ "master" ]
  workflow_dispatch:  # 手动触发

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Install pnpm + deps
      uses: pnpm/action-setup@v4.2.0
      with:
        version: 10
        run_install: true

    - name: Use Node.js
      uses: actions/setup-node@v6.1.0
      with:
        node-version: 24
        cache: "pnpm"
    
    - name: install Rust stable
      uses: dtolnay/rust-toolchain@stable
      with:
        toolchain: stable

    - name: install dependencies
      run: |
        pnpm install

    - name: Install Android dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y libwebkit2gtk-4.1-dev libappindicator3-dev librsvg2-dev patchelf

    - name: Setup Android targets
      run: |
        rustup target add aarch64-linux-android

    - name: Install Tauri CLI
      run: |
        pnpm add -g @tauri-apps/cli

    # - name: Build Android APK
    #   uses: tauri-apps/tauri-action@v0
    #   env:
    #     GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    #   with:
    #     tagName: app-v__VERSION__
    #     releaseName: "App v__VERSION__"
    #     releaseBody: "Download and install this version."
    #     releaseDraft: true
    #     prerelease: false
    #     args: --target aarch64-linux-android

    - name: Init Android Project
      run: |
        pnpm run tauri android:init

    # - name: Build Android APK
    #   run: |
    #     pnpm tauri android build

    # - name: Upload APK artifact
    #   uses: actions/upload-artifact@v4
    #   with:
    #     name: android-apk
    #     path: src-tauri/target/aarch64-linux-android/release/bundle/apk/*.apk
    #     if-no-files-found: error

    # - name: Upload bundle artifact
    #   uses: actions/upload-artifact@v4
    #   with:
    #     name: android-bundle
    #     path: src-tauri/target/aarch64-linux-android/release/bundle
    #     if-no-files-found: error
